### ISSUE TITLE
CSS Responsiveness in Mobile Screen

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/Recipe-Finder-WebApp#2]
### Description

Our project needs better responsiveness on various devices and screen sizes.

### Scope

- Update header navigation for smaller screens.
- Fit Background Properly in Website
- Implement media queries for breakpoints.

### Acceptance Criteria

- You can also Create an Separate issue for any Changes
- All scope are fix correctly, if you have made proper PR and changes then your PR merge by `hacktoberfest` and `hacktoberfest-accepted` label

### Labels

- CSS
- Responsive Design
- Hacktoberfest

**Comment by jaken92** [comment]
Id like to work on this! Do you want a hamburger menu for the nav on smaller screens or something else in mind?

**Comment by imhardikdesai** [comment]
> Id like to work on this! Do you want a hamburger menu for the nav on smaller screens or something else in mind?

Yes i want hamburger menu on smaller screen, i will assign you this issue

**Comment by NegativE333** [comment]
Hey, can i work on this issue?

**Comment by NegativE333** [comment]
I've noticed that plain CSS has been initially used for styling on this website. However, I would like to propose using Tailwind CSS to enhance its responsiveness. What are your thoughts on transitioning to Tailwind CSS for this purpose?

**Comment by NegativE333** [comment]
Hi @imhardikdesai ,

I hope you're doing well. I wanted to share some recent changes I've made to the project with you. I've been working on improving the mobile responsiveness of the website.

Changes Made:
- Added React icons to the navbar.
Before
![image](https://github.com/imhardikdesai/Recipe-Finder-WebApp/assets/102456428/83d0d867-dea4-4174-a25e-235c970afcb7)
After
![image](https://github.com/imhardikdesai/Recipe-Finder-WebApp/assets/102456428/3c3bb30c-2dfc-4f34-bfe1-57b73137987d)

- Introduced a hamburger icon for mobile navigation.
Before
![image](https://github.com/imhardikdesai/Recipe-Finder-WebApp/assets/102456428/7a378a6e-b5ed-4242-9ccf-006ab5ca2440)
After
![image](https://github.com/imhardikdesai/Recipe-Finder-WebApp/assets/102456428/c2f5652f-0e09-4b09-9116-af137f070428)

- Aligned the content within cards for improved mobile alignment.
Before
![Before](https://github.com/imhardikdesai/Recipe-Finder-WebApp/assets/102456428/c6853ee6-1891-45b4-b4f7-aca36795cc80)
After
![image](https://github.com/imhardikdesai/Recipe-Finder-WebApp/assets/102456428/5eb15265-c531-41a7-96be-cb7db90bd6bf)



These changes are aimed at enhancing the user experience on mobile devices and making the project more user-friendly. I'd like to know if you think these changes align with the project's goals and design principles. Your feedback and insights would be greatly appreciated.

If these changes are deemed suitable, would it be acceptable to create a pull request for your review? I'm open to further adjustments based on your suggestions.

**Comment by imhardikdesai** [comment]
@NegativE333 You did great work appreciate it.
I want to merge your changes so please create a pull request.

**Comment by imhardikdesai** [comment]
@NegativE333 Also for the Tailwind CSS suggestion, we can convert it into a tailwind. if you want to do that then create a separate issue and then I will assign that to you
Thank You
